# Generated by Django 4.0 on 2021-12-10 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Water',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название продукта')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена за 1 бутылку')),
                ('is_in_stock', models.BooleanField(verbose_name='Есть на складе?')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Когда последний раз обновлялось значение акциия?')),
            ],
        ),
    ]
