# Generated by Django 4.0 on 2021-12-20 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewWater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=250)),
                ('text', models.CharField(max_length=250)),
            ],
        ),
    ]
